;; Even Fibonacci numbers
;; Problem 2

;; Each new term in the Fibonacci sequence is generated by adding the
;; previous two terms. By starting with 1 and 2, the first 10 terms
;; will be:

;; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

;; By considering the terms in the Fibonacci sequence whose values do
;; not exceed four million, find the sum of the even-valued terms.

(defun p002 ()
  (interactive)
  (let ((s 0)
        (n 3))
    (while (< (fibonacci n) (* 4 (expt 10 6)))
      (setq s (+ s (fibonacci n)))
      (setq n (+ n 3)))
    (message (format "%s" s))))

(defun fibonacci (m)
  (pcase m
    (`1 1)
    (`2 1)
    ((pred oddp) (let ((n (/ (+ m 1) 2)))
                   (+ (expt (fibonacci n) 2)
                      (expt (fibonacci (- n 1)) 2))))
    ((pred evenp) (let ((n (/ m 2)))
                    (* (+ (* 2 (fibonacci (- n 1)))
                          (fibonacci n))
                       (fibonacci n))))))
