(defun problem-002 ()
  (interactive)
  (let ((s 0)
        (n 3))
    (while (< (fibonacci n) (* 4 (expt 10 6)))
      (setq s (+ s (fibonacci n)))
      (setq n (+ n 3)))
    (message (format "%s" s))))

(defun fibonacci (m)
  (pcase m
    (`1 1)
    (`2 1)
    ((pred oddp) (let ((n (/ (+ m 1) 2)))
                   (+ (expt (fibonacci n) 2)
                      (expt (fibonacci (- n 1)) 2))))
    ((pred evenp) (let ((n (/ m 2)))
                    (* (+ (* 2 (fibonacci (- n 1)))
                          (fibonacci n))
                       (fibonacci n))))))
