// Even Fibonacci numbers
// Problem 2

// Each new term in the Fibonacci sequence is generated by adding the
// previous two terms. By starting with 1 and 2, the first 10 terms
// will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do
// not exceed four million, find the sum of the even-valued terms.

// 2, 8, 34, 144, ...

// a, b, c, b + c, b + 2 * c, 2 * b + 3 * c

public class P002 {

    static int solution() {
        int a = 0;
        int b = 1;
        int c = 1;
        int s = 0;
        int lim = 4 * (int)Math.pow(10, 6);
        while (a < lim) {
            s += a;
            int temp = b;
            a = b + c;
            b = b + 2 * c;
            c = 2 * temp + 3 * c;
        }
        return s;
    }

    public static void main(String[] args) {
        int sol = solution();
        assert sol == 4613732;
        System.out.println(sol);
    }

}
