# Even Fibonacci numbers
# Problem 2

# Each new term in the Fibonacci sequence is generated by adding the
# previous two terms. By starting with 1 and 2, the first 10 terms
# will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do
# not exceed four million, find the sum of the even-valued terms.

# 2, 8, 34, 144, ...

# a, b, c, b + c, b + 2 * c, 2 * b + 3 * c

from itertools import takewhile

def evenFibGen():
    a, b = 1, 2
    while True:
        yield b
        a, b = a + 2 * b, 2 * a + 3 * b

def p002():
    evenFibs = evenFibGen()
    return sum(takewhile(lambda n: n < 4 * 10 ** 6, evenFibs))
